---

version: "2.4"
services:
  morph:
    image: nspccdev/neo-go:${NEOGO_VERSION}
    container_name: morph
    domainname: neofs
    hostname: morph
    restart: always
    stop_signal: SIGKILL
    environment:
      - ACC=/config/morph_chain.gz
    volumes:
      - ./vendor/morph_chain.gz:/config/morph_chain.gz
      - ./morph/protocol.privnet.yml:/config/protocol.privnet.yml
      - ./morph/node-wallet.json:/config/node-wallet.json
    ports:
      - "30333:30333" # RPC
    healthcheck:
      test: [ "CMD-SHELL", "neo-go query committee -r http://127.0.0.1:30333 | grep 02b3622bf4017bdfe317c58aed5f4c753f206b7db896046fa7d774bbc4bf7f8dc2" ]
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 10s

  ir:
    image: nspccdev/neofs-aio:${AIO_VERSION}
    container_name: ir
    domainname: neofs
    hostname: ir
    restart: on-failure
    stop_signal: SIGKILL
    environment:
      - NEOFS_IR_MORPH_ENDPOINT_CLIENT_0_ADDRESS=ws://morph:30333/ws
    volumes:
      - ./morph/node-wallet.json:/config/node-wallet.json
      - ./ir/cli-cfg.yaml:/config/cli-cfg.yaml
      - ./ir/config.yaml:/config/config.yaml
      - ./vendor/locode_db:/config/locode.db
    entrypoint: /bin/neofs-ir
    command: --config /config/config.yaml
    healthcheck:
      test: [ "CMD-SHELL", "/bin/neofs-cli control healthcheck --ir --endpoint localhost:16512 -c /config/cli-cfg.yaml | grep 'Health status: READY'" ]
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 20s
    depends_on:
      morph:
        condition: service_healthy

  sn:
    image: nspccdev/neofs-aio:${AIO_VERSION}
    domainname: neofs
    hostname: sn
    container_name: sn
    restart: on-failure
    stop_signal: SIGKILL
    environment:
      - NEOFS_MORPH_RPC_ENDPOINT_0_ADDRESS=ws://morph:30333/ws
      - NEOFS_NODE_ADDRESSES=grpc://sn:8080
      - NEOFS_GRPC_0_ENDPOINT=:8080
      - NEOFS_CONTROL_GRPC_ENDPOINT=:16513
    volumes:
      - ./sn/cli-cfg.yaml:/config/cli-cfg.yaml
      - ./sn/wallet.json:/config/wallet-sn.json
      - ./sn/config.yaml:/config/config.yaml
      - data:/data
    ports:
      - "8080:8080"   # NeoFS API RPC
      - "16513:16513" # Control service
    entrypoint: /bin/neofs-node
    command: --config /config/config.yaml
    healthcheck:
      test: [ "CMD-SHELL", "/bin/neofs-cli control healthcheck --endpoint localhost:16513 -c /config/cli-cfg.yaml | grep 'Health status: READY'" ]
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 10s
    depends_on:
      ir:
        condition: service_healthy

  http_gw:
    image: nspccdev/neofs-http-gw:${HTTPGW_VERSION}
    domainname: neofs
    hostname: http_gw
    container_name: http_gw
    restart: on-failure
    stop_signal: SIGKILL
    env_file: [ "./http/http.env" ]
    environment:
      - HTTP_GW_LISTEN_ADDRESS=:8081
      - HTTP_GW_PEERS_0_ADDRESS=sn:8080
      - HTTP_GW_RPC_ENDPOINT=http://morph:30333
    volumes:
      - ./http/wallet.json:/config/wallet.json
    ports:
      - "8081:8081" # HTTP Gateway endpoint
    depends_on:
      - sn

  rest_gw:
    image: nspccdev/neofs-rest-gw:${RESTGW_VERSION}
    domainname: neofs
    hostname: rest_gw
    container_name: rest_gw
    restart: on-failure
    stop_signal: SIGKILL
    env_file: [ "./rest-gw/rest.env" ]
    environment:
      - REST_GW_LISTEN_ADDRESS=:8090
      - REST_GW_PEERS_0_ADDRESS=sn:8080
    volumes:
      - ./rest-gw/node-wallet.json:/config/wallet.json
    ports:
      - "8090:8090" # REST Gateway endpoint
    depends_on:
      - sn

  nginx_gw:
    image: nginx:stable-alpine
    domainname: neofs
    hostname: nginx_gw
    container_name: nginx_gw
    restart: on-failure
    stop_signal: SIGKILL
    volumes:
      - ./http/nginx.cross.conf:/etc/nginx/nginx.conf
      - cache:/cache
    ports:
      - "8082:8082" # nginx gateway endpoint
    depends_on:
      - http_gw

  s3_gw:
    image: nspccdev/neofs-s3-gw:${S3GW_VERSION}
    domainname: neofs
    hostname: s3_gw
    container_name: s3_gw
    restart: on-failure
    stop_signal: SIGKILL
    env_file: [ "./s3/s3.env" ]
    environment:
      - S3_GW_LISTEN_ADDRESS=:9000
      - S3_GW_PEERS_0_ADDRESS=sn:8080
      - S3_GW_RPC_ENDPOINT=http://morph:30333
      - S3_GW_TREE_SERVICE=sn:8080
    volumes:
      - ./s3/wallet.json:/config/wallet.json
    ports:
      - "9000:9000" # S3 Gateway endpoint
    depends_on:
      - sn

volumes:
  data:
  cache:
